### PR TITLE
Make GoogleMap easier to use!

### PR DESCRIPTION
**Pull request by khoaakt**
Not allowed resize is a bad idea xD

### CODE REVIEW

**Comment by andersevenrud** [comment]
Hi.

I cannot accept these commits without doing modifications as the messages does not fall within the guidelines of contributions.

I can fix this manually myself, but that would make your branch incompatible witht this one, and you would have to reset.

A good strategy for avoiding problems like this is to think about your messages a few minutes before commiting. Remember, everyone visiting github will see this and they will not understand what changes has occured or why :)

Some examples are:

> Fix Something...

What is "something" ?

> ayyy

What does this even mean ?

> Add files via upload

Add what files, upload where ?

> html5 game

Which game ?

**Comment by andersevenrud** [comment]
If you're not sure about what to write, just ask in the community ;)

**Comment by andersevenrud** [comment]
Also, I see you're using `jsdosbox` for quite a few of these. Maybe consider making a application where you can chose what game to start instead of having them all separated ? :)

**Comment by khoaakt** [comment]
Sorry, I missed that I accidentally click on the pull. Closed

**Pull request closed without merging**
